group: "Mammal" 
genome: "Homo_sapiens" 
assembly: "hg38" 
se_input: "/public/home/chenzr/PSI_Seq_brainCell/A1-A12-totalRNA-result/A1.cutadapt.extendedFrags.collapse.cutBarcodes.fa.gz" 
se_treat: "/public/home/chenzr/PSI_Seq_brainCell/A1-A12-totalRNA-result/A2.cutadapt.extendedFrags.collapse.cutBarcodes.fa.gz" 
se_input_prefix: "A1" 
se_treat_prefix: "A2" 
se_br5_input: "0" 
se_br3_input: "0" 
se_ad5_input: "" 
se_ad3_input: "" 
se_br5_treat: "0" 
se_br3_treat: "0" 
se_ad5_treat: "" 
se_ad3_treat: "" 
sites_identification: "true" 
sites_annotation: "true" 
sites_target_prediction: "true" 
br_remove_input: "false" 
br_remove_treat: "false" 
ad_remove_input: "false" 
ad_remove_treat: "false" 
svm: "false" 
metagene: "true" 
ann: "true" 
user_defined: "false" 
treatpre_Fold_thres: "0" 
preFold_FC_thres: "0" 
treataft_Fold_thres: "0" 
aftFold_FC_thres: "0" 
treatstoprate_thres: "0" 
stoprate_FC_thres: "0"